### ISSUE TITLE
Handle failure without StatusRuntimeExceptions

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb-proto#4]
Currently, if you're trying to create an entity which already exists or trying to drop an entity which not exists (among other things), cottontaildb throws a StatusRuntimeException over the channel. This is because the .proto-definition does not allow for transparent failure.

One solution would be to include a Success Flag in the SuccessStatus Message or return a StatusMessage which can include information about unsuccessfull operations without throwing exceptions.

**Comment by ppanopticon** [comment]
What would be the advantage of this? 

Some JDBC implementations throw an exception when, for example, a query doesn't return a result. You handle them and get on, as you would with these status messages.

**Comment by silvanheller** [comment]
I guess it's a philosophical argument. I would expect Exceptions to be thrown when something exceptional happens - and an entity not being dropped because it does not exist is an expected behavior. I just checked the current proto-file and most calls could returns a `Status` (the original issue is from 2019), but with no indicator for what went wrong if it is not successful. Additionally, cottontail is currently not using this but works with Errors. 

I see the following options:
- Cottontail uses Status-Messages as Responses (using io.grpc.Status as information, similar to what currently is done) and Errors only when something seriously goes wrong
- Cottontail continues using Errors for communication but then I would drop the statuses in reply as they have no value

**Comment by ppanopticon** [comment]
I agree that it is unclear how failure is communicated given the presence of our own status object implementation. To make things more consistent, I'd suggest the following:

- Make all existing gRPC calls that return a Status, return a google.protobuf.Empty instead.
- Consequently use StatusExceptions to communicate any type if failure scenario.

As I understand it, _io.grpc.Status_ can either be communicated as a return value or as an exception. Both are valid approaches and it is ultimately a matter of preference. I'd prefer the latter.

Because, while you may be right that, e.g., failure to create an entity that already exists may not be exceptional from a database perspective, it probably is unexpected from the perspective of the calling application, which obviously executed under the assumption, that said entity did not exist.

**Comment by silvanheller** [comment]
Closing as the discussion is pretty old and resolved
